version: '3.1'
services:

  tempo-app:
    container_name: tempo-springboot-app
    build: ./
    ports:
      - 8080:8080
    depends_on:
      - tempo-postgresql
    environment:
      - DB_SERVER=tempo-postgresql
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres



  tempo-postgresql:
    container_name: tempo-postgresql
    image: "postgres:10.21"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres


volumes:
  postgres-data: